application: eabfoose-01231
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /stylesheets
  static_dir: stylesheets

# you missed this section. It allows all .css files inside stylesheets
- url: /stylesheets/(.*\.(css)) 
  static_files: stylesheets/\1
  upload: stylesheets/(.*\.(css))

- url: /stylesheets/(.*\.(js))
  static_files: stylesheets/\1
  upload: stylesheets/(.*\.(js))

- url: /favicon.ico
  static_files: media/img/favicon.ico
  upload: media/img/favicon.ico

- url: /media/img/
  static_dir: media/img  


- url: /auth/.*
  script: FooseMain.application
  login: required

- url: /_min/.*
  script: crontasks.application
  login: admin

- url: /tasks/.*
  script: FooseMain.application
  login: admin


- url: /.*
  script: FooseMain.application